name       : fsharp
version    : 10.0.2
release    : 4
source     :
    - https://github.com/fsharp/fsharp/archive/10.0.2.tar.gz : 1ae5e5e842df91f9f27aafa97109d74812219bc695384c5d8f1e8fbc5991d0ce
license    : Apache-2.0
component  : programming.tools
summary    : F# Compiler, Core Library & Tools
networking : yes
description: |
    The Open Edition of the F# compiler, core library and tools
builddeps  :
    - pkgconfig(mono)
    - mono-msbuild
rundeps    :
    - mono
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
build      : |
    %make
install    : |
    %make_install
