name       : fsharp
version    : 10.2.3
release    : 5
source     :
    - https://github.com/fsharp/fsharp/archive/10.2.3.tar.gz : 527e4bad7a6d71668e905608c82db7c6eda44d9fd2ed9ce3c758e291e024cc4d
license    : Apache-2.0
component  : programming.tools
summary    : F# Compiler, Core Library & Tools
networking : yes
description: |
    The Open Edition of the F# compiler, core library and tools
builddeps  :
    - pkgconfig(mono)
    - mono-msbuild
rundeps    :
    - mono
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
build      : |
    %make
install    : |
    %make_install
